import jsPDF from 'jspdf';

interface ExportData {
  title: string;
  date: string;
  moistureReadings?: Array<{ date: string; level: number }>;
  fertilityReadings?: Array<{ date: string; level: number }>;
  crops?: Array<{ name: string; type: string; status: string }>;
  schedules?: Array<{ title: string; days: string; time: string }>;
}

export const exportToPDF = (data: ExportData) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPosition = 20;

  // Header
  doc.setFontSize(20);
  doc.setTextColor(45, 90, 39); // Primary color
  doc.text('AgroEye Report', pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 10;
  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(data.date, pageWidth / 2, yPosition, { align: 'center' });
  
  yPosition += 15;
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(data.title, 20, yPosition);
  
  yPosition += 10;

  // Moisture Readings
  if (data.moistureReadings && data.moistureReadings.length > 0) {
    yPosition += 10;
    doc.setFontSize(14);
    doc.setTextColor(45, 90, 39);
    doc.text('Moisture Readings', 20, yPosition);
    yPosition += 8;
    
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    data.moistureReadings.forEach((reading) => {
      if (yPosition > 270) {
        doc.addPage();
        yPosition = 20;
      }
      doc.text(`${reading.date}: ${reading.level}%`, 25, yPosition);
      yPosition += 6;
    });
  }

  // Fertility Readings
  if (data.fertilityReadings && data.fertilityReadings.length > 0) {
    yPosition += 10;
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }
    doc.setFontSize(14);
    doc.setTextColor(45, 90, 39);
    doc.text('Fertility Readings', 20, yPosition);
    yPosition += 8;
    
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    data.fertilityReadings.forEach((reading) => {
      if (yPosition > 270) {
        doc.addPage();
        yPosition = 20;
      }
      doc.text(`${reading.date}: ${reading.level}%`, 25, yPosition);
      yPosition += 6;
    });
  }

  // Crops
  if (data.crops && data.crops.length > 0) {
    yPosition += 10;
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }
    doc.setFontSize(14);
    doc.setTextColor(45, 90, 39);
    doc.text('Active Crops', 20, yPosition);
    yPosition += 8;
    
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    data.crops.forEach((crop) => {
      if (yPosition > 270) {
        doc.addPage();
        yPosition = 20;
      }
      doc.text(`${crop.name} (${crop.type}) - ${crop.status}`, 25, yPosition);
      yPosition += 6;
    });
  }

  // Schedules
  if (data.schedules && data.schedules.length > 0) {
    yPosition += 10;
    if (yPosition > 250) {
      doc.addPage();
      yPosition = 20;
    }
    doc.setFontSize(14);
    doc.setTextColor(45, 90, 39);
    doc.text('Watering Schedules', 20, yPosition);
    yPosition += 8;
    
    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    data.schedules.forEach((schedule) => {
      if (yPosition > 270) {
        doc.addPage();
        yPosition = 20;
      }
      doc.text(`${schedule.title} - ${schedule.days} at ${schedule.time}`, 25, yPosition);
      yPosition += 6;
    });
  }

  // Footer
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by AgroEye - Page ${i} of ${totalPages}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  return doc;
};
